'use strict';
// Cohort observations. Conversions are performed separately in simulation.js.
// No value here is a validated individual risk or a cross-trial ranking.
const Evidence=(()=>{
 const pm=id=>'https://pubmed.ncbi.nlm.nih.gov/'+id+'/';
 const arr=value=>({kind:'rate',value,label:'Annualized relapse rate',unit:'relapses / person-year'});
 const risk=(value,years,label,window)=>({kind:'risk',value,years,label,window:window||years+' years'});
 const adverse=(metric,label,severity,source)=>({...metric,label,severity,source});
 const w96=96/52,w108=108/52;
 const records={
 ubl:{trial:'ULTIMATE I / II',population:'Relapsing MS',source:pm('36001711'),relapse:arr(.08),progression:risk(.052,w96,'12-week confirmed disability worsening','96 weeks'),complication:adverse(risk(.05,w96,'','96 weeks'),'Serious infection','serious'),note:'ARR uses ULTIMATE I (II: 0.09). Disability and safety are pooled. Disability superiority was not demonstrated.'},
 ofa:{trial:'ASCLEPIOS I / II',population:'Relapsing MS',source:pm('32757523'),relapse:arr(.11),progression:risk(.109,1.6,'3-month confirmed disability worsening','variable follow-up; median 1.6 years'),complication:adverse(risk(.025,1.6,'','variable follow-up; median 1.6 years'),'Serious infection','serious'),note:'ARR uses ASCLEPIOS I (II: 0.10). Using median follow-up for pooled proportions is a rough simulation approximation, not a survival estimate.'},
 ocr:{trial:'OPERA I / II',population:'Relapsing MS',source:pm('28002679'),relapse:arr(.16),progression:risk(.091,w96,'12-week confirmed disability progression','96 weeks'),complication:adverse(risk(.013,w96,'','96 weeks'),'Serious infection','serious'),note:'Relapsing MS cohort. PPMS uses the separate ORATORIO reference below.'},
 rtx:{trial:'RIFUND-MS',population:'Early active RRMS / CIS; age 18–50; diagnosis ≤10 years',source:pm('35841908'),relapse:risk(.03,2,'Participants with ≥1 relapse','24 months'),progression:null,complication:adverse({kind:'rate',value:.409,unit:'events / person-year',window:'24-month trial'},'Infusion reaction','minor'),note:'Off-label MS use. Relapse figure is a participant proportion, not ARR. Reactions: 40.9 events/100 person-years; recurrent events are not the proportion of participants. No disability probability entered.'},
 nat:{trial:'AFFIRM',population:'Relapsing MS',source:pm('16510744'),relapse:arr(.22),progression:risk(.17,2,'12-week sustained disability progression','2 years'),complication:adverse(risk(.01,2,'','2 years'),'Serious hypersensitivity reaction','serious'),note:'Relapse ARR 0.22 is from the US label, Study MS1 at 2 years. Rare PML is NOT sampled; JCV status and exposure still affect the safety decision score.',extraSources:[S.nat]},
 cla:{trial:'CLARITY',population:'Relapsing-remitting MS; 3.5 mg/kg course',source:pm('20089960'),relapse:arr(.14),progression:null,complication:adverse(risk(.216,w96,'','96 weeks'),'Lymphocytopenia','moderate'),note:'No disability probability entered from the extracted report. This selected event is not the complete safety profile. Two annual courses; ongoing surveillance.'},
 ale:{trial:'CARE-MS II',population:'RRMS after inadequate response to prior DMT',source:pm('23122650'),relapse:risk(.35,2,'Participants with ≥1 relapse','24 months'),progression:risk(.13,2,'6-month sustained disability accumulation','24 months'),complication:adverse(risk(.16,2,'','24 months'),'Thyroid disorder','moderate'),note:'The 35% relapse figure is an observed participant proportion. Delayed autoimmune events can occur beyond this game; monitoring lasts 48 months after the last infusion.'},
 oza:{trial:'RADIANCE / US label',population:'Relapsing MS',source:pm('31492652'),relapse:arr(.17),progression:risk(.076,2,'3-month confirmed disability progression','pooled 2-year analysis; variable study exposure'),complication:adverse({kind:'initiation',value:.006,window:'day of initiation'},'Initiation bradycardia','moderate',S.oza[1]),note:'Trial 1.0 mg hydrochloride corresponds to the labeled 0.92 mg ozanimod dose. Pooled disability difference was not significant. The bradycardia draw occurs only when starting/restarting.',extraSources:[S.oza]},
 pon:{trial:'OPTIMUM',population:'Active relapsing MS; age 18–55; EDSS 0–5.5',source:pm('33779698'),relapse:arr(.202),progression:risk(.101,w108,'12-week confirmed disability accumulation','108 weeks'),complication:adverse(risk(.087,w108,'','108 weeks'),'Adverse event requiring discontinuation','moderate'),note:'Disability difference was not significant. The selected complication is discontinuation due to any adverse event, not serious infection.'},
 sip:{trial:'EXPAND',population:'SPMS; age 18–60; EDSS 3–6.5; active and non-active participants',source:pm('29576505'),relapse:arr(.071),progression:risk(.26,21/12,'3-month confirmed disability progression','variable follow-up; median 21 months'),complication:adverse(risk(.018,21/12,'','variable trial exposure; median 21 months'),'Macular edema','moderate',S.sip[1]),note:'Overall SPMS cohort, not the active-SPMS subgroup. Median-time conversion is approximate. Macular edema was concentrated early, so constant hazard loses that timing.',extraSources:[S.sip]},
 fin:{trial:'FREEDOMS / US label',population:'Relapsing-remitting MS; 0.5 mg daily',source:pm('20089952'),relapse:arr(.18),progression:risk(.177,2,'3-month confirmed disability progression','24 months'),complication:adverse({kind:'initiation',value:.006,window:'first dose'},'Symptomatic first-dose bradycardia','moderate',S.fin[1]),note:'First-dose event is sampled on initiation/restart only. Other infections, eye and liver risks remain relevant.',extraSources:[S.fin]},
 drf:{trial:'DMF efficacy bridge / EVOLVE-MS-2',population:'Relapsing-remitting MS',source:pm('31953790'),relapse:arr(.17),progression:risk(.16,2,'12-week confirmed disability progression (DMF proxy)','24 months in DEFINE, not a DRF trial'),complication:adverse({kind:'initiation',value:.348,window:'first 5 weeks'},'Gastrointestinal adverse event','minor'),note:'Relapse/disability values are explicitly borrowed from DMF DEFINE through the shared active metabolite; not independently measured DRF efficacy. GI events: 34.8% over 5 weeks, sampled once per start, never annualized.',extraSources:[['DEFINE · DMF efficacy bridge',pm('22992073')],S.drf]},
 dmf:{trial:'DEFINE / EU label',population:'Relapsing-remitting MS; 240 mg twice daily',source:pm('22992073'),relapse:arr(.17),progression:risk(.16,2,'12-week confirmed disability progression','24 months'),complication:adverse(risk(.02,2,'','2-year phase III studies'),'Serious infection','serious',S.dmf[1]),note:'Safety figure is from pooled phase III label data: serious infection 2% with DMF and 2% with placebo.',extraSources:[S.dmf]},
 ter:{trial:'TEMSO',population:'Relapsing MS; 14 mg daily reference',source:pm('21991951'),relapse:arr(.37),progression:risk(.202,w108,'12-week confirmed disability progression','108 weeks'),complication:adverse(risk(.022,w108,'','108 weeks'),'Serious infection','serious'),note:'The outcome model uses the 14 mg arm. The dossier also lists the US 7 mg option; those disability results are not interchangeable.'},
 ga:{trial:'GALA',population:'RRMS; EDSS ≤5.5; 40 mg SC three times weekly',source:pm('23686821'),relapse:arr(.331),progression:null,complication:adverse(risk(.355,1,'','12 months'),'Injection-site reaction','minor'),note:'Model uses the 40 mg three-times-weekly regimen. No disability probability entered. Continuing these rates into year 2 extrapolates beyond this trial.'},
 ifn:{trial:'OPERA comparator arm',population:'Relapsing MS; 44 µg SC three times weekly',source:pm('28002679'),relapse:arr(.29),progression:risk(.136,w96,'12-week confirmed disability progression','96 weeks'),complication:adverse(risk(.029,w96,'','96 weeks'),'Serious infection','serious'),note:'These are the interferon comparator data from OPERA, not a direct comparison with the other trials displayed in this arsenal.'}
 };
 const ppms={trial:'ORATORIO',population:'PPMS; age 18–55; EDSS 3–6.5; duration limits applied',source:pm('28002688'),relapse:null,progression:risk(.329,120/52,'12-week confirmed disability progression','trial minimum 120 weeks'),complication:adverse(risk(.40,3,'','PPMS trial; median treatment 3 years'),'Infusion reaction','minor',S.ocr[1]),note:'Progression conversion uses the minimum trial duration. The PPMS infusion-reaction figure uses median exposure of 3 years; reactions cluster early, so constant hazard is approximate. Relapse is not modeled.',extraSources:[S.ocr]};
 const noDmt={
 RRMS:{trial:'DEFINE placebo arm',population:'Trial RRMS placebo cohort',source:pm('22992073'),relapse:arr(.36),progression:risk(.27,2,'12-week confirmed disability progression','24 months'),complication:null,note:'Historical placebo is only an illustrative reference; it is not a natural-history prediction for an untreated person today.'},
 PPMS:{...ppms,complication:null,trial:'ORATORIO placebo arm',progression:risk(.393,120/52,'12-week confirmed disability progression','trial minimum 120 weeks'),note:'Historical PPMS placebo cohort; minimum-duration conversion is approximate.'},
 SPMS:{trial:'EXPAND placebo arm',population:'Mixed active / non-active SPMS',source:pm('29576505'),relapse:null,progression:risk(.32,21/12,'3-month confirmed disability progression','variable follow-up; median 21 months'),complication:null,note:'This mixed SPMS placebo cohort cannot provide an individual risk for non-active SPMS. Median-time conversion is approximate.'}
 };
 function get(patient,drug){
  if(drug.research)return null;
  if(drug.id==='review')return {...noDmt[patient.type==='RRMS'?'RRMS':patient.type==='PPMS'?'PPMS':'SPMS']};
  const base=records[drug.id];
  if(patient.type==='PPMS')return drug.id==='ocr'?{...ppms}:{...noDmt.PPMS,complication:base.complication,complicationSource:base.source,unsupported:true,note:'No established PPMS efficacy is assigned to this choice. A placebo progression proxy is used; the safety event is borrowed from a different trial population.'};
  if(patient.type==='Non-active SPMS')return {...noDmt.SPMS,complication:base.complication,complicationSource:base.source,unsupported:true,note:'No proven efficacy in this non-active SPMS profile is assumed. Progression uses a mixed-SPMS placebo proxy; drug safety comes from its source trial.'};
  if(patient.type==='Active SPMS'&&drug.id!=='sip')return {...base,progression:null,extrapolated:true,note:base.note+' Relapse/safety data are transferred from relapsing trials; SPMS disability benefit is not quantified.'};
  if(patient.type==='RRMS'&&drug.id==='sip')return {...base,relapse:null,progression:null,extrapolated:true,note:'EXPAND enrolled SPMS. No numerical RRMS relapse or disability forecast is transferred from it; only a safety teaching draw is available.'};
  return {...base};
 }
 return {records,get,ppms,noDmt};
})();
